<?xml version="1.0" encoding="UTF-8"?><testsuite failures="1" name="cucumber.runtime.formatter.JUnitFormatter" skipped="0" tests="5" time="24.872973">
<testcase classname="Jira Test With Single Scenario Outline" name="01. Validate user name for different sets of data" time="12.061043">
<failure message="io.restassured.path.json.exception.JsonPathException: Failed to parse the JSON document&#13;&#10;&#9;at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:930)&#13;&#10;&#9;at io.restassured.path.json.JsonPath$4.doParseWith(JsonPath.java:895)&#13;&#10;&#9;at io.restassured.path.json.JsonPath$JsonParser.parseWith(JsonPath.java:975)&#13;&#10;&#9;at io.restassured.path.json.JsonPath.get(JsonPath.java:201)&#13;&#10;&#9;at io.restassured.path.json.JsonPath.getString(JsonPath.java:351)&#13;&#10;&#9;at com.adidas.serenity.steps.Hooks.createTestExecutionAndLinkTestWithUserStory(Hooks.java:56)&#13;&#10;&#9;at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;&#10;&#9;at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)&#13;&#10;&#9;at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)&#13;&#10;&#9;at java.lang.reflect.Method.invoke(Method.java:498)&#13;&#10;&#9;at cucumber.runtime.Utils$1.call(Utils.java:31)&#13;&#10;&#9;at cucumber.runtime.Timeout.timeout(Timeout.java:16)&#13;&#10;&#9;at cucumber.runtime.Utils.invoke(Utils.java:25)&#13;&#10;&#9;at cucumber.runtime.java.JavaHookDefinition.execute(JavaHookDefinition.java:60)&#13;&#10;&#9;at cucumber.runtime.HookDefinitionMatch.runStep(HookDefinitionMatch.java:17)&#13;&#10;&#9;at cucumber.runner.UnskipableStep.executeStep(UnskipableStep.java:22)&#13;&#10;&#9;at cucumber.api.TestStep.run(TestStep.java:83)&#13;&#10;&#9;at cucumber.api.TestCase.run(TestCase.java:58)&#13;&#10;&#9;at cucumber.runner.Runner.runPickle(Runner.java:80)&#13;&#10;&#9;at cucumber.runtime.Runtime.runFeature(Runtime.java:119)&#13;&#10;&#9;at cucumber.runtime.Runtime.run(Runtime.java:104)&#13;&#10;&#9;at cucumber.api.cli.Main.run(Main.java:36)&#13;&#10;&#9;at cucumber.api.cli.Main.main(Main.java:18)&#13;&#10;Caused by: groovy.json.JsonException: Lexing failed on line: 1, column: 1, while reading '&lt;', no possible valid JSON value or punctuation could be recognized.&#13;&#10;&#9;at groovy.json.JsonLexer.nextToken(JsonLexer.java:83)&#13;&#10;&#9;at groovy.json.JsonLexer$nextToken.call(Unknown Source)&#13;&#10;&#9;at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)&#13;&#10;&#9;at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)&#13;&#10;&#9;at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:117)&#13;&#10;&#9;at io.restassured.internal.path.json.ConfigurableJsonSlurper.parse(ConfigurableJsonSlurper.groovy:97)&#13;&#10;&#9;at io.restassured.internal.path.json.ConfigurableJsonSlurper$parse.callCurrent(Unknown Source)&#13;&#10;&#9;at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:52)&#13;&#10;&#9;at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:154)&#13;&#10;&#9;at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:166)&#13;&#10;&#9;at io.restassured.internal.path.json.ConfigurableJsonSlurper.parseText(ConfigurableJsonSlurper.groovy:83)&#13;&#10;&#9;at io.restassured.path.json.JsonPath$4$1.method(JsonPath.java:893)&#13;&#10;&#9;at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:928)&#13;&#10;&#9;... 22 more&#13;&#10;"><![CDATA[Given Username is Test1.....................................................skipped

StackTrace:
io.restassured.path.json.exception.JsonPathException: Failed to parse the JSON document
	at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:930)
	at io.restassured.path.json.JsonPath$4.doParseWith(JsonPath.java:895)
	at io.restassured.path.json.JsonPath$JsonParser.parseWith(JsonPath.java:975)
	at io.restassured.path.json.JsonPath.get(JsonPath.java:201)
	at io.restassured.path.json.JsonPath.getString(JsonPath.java:351)
	at com.adidas.serenity.steps.Hooks.createTestExecutionAndLinkTestWithUserStory(Hooks.java:56)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at cucumber.runtime.Utils$1.call(Utils.java:31)
	at cucumber.runtime.Timeout.timeout(Timeout.java:16)
	at cucumber.runtime.Utils.invoke(Utils.java:25)
	at cucumber.runtime.java.JavaHookDefinition.execute(JavaHookDefinition.java:60)
	at cucumber.runtime.HookDefinitionMatch.runStep(HookDefinitionMatch.java:17)
	at cucumber.runner.UnskipableStep.executeStep(UnskipableStep.java:22)
	at cucumber.api.TestStep.run(TestStep.java:83)
	at cucumber.api.TestCase.run(TestCase.java:58)
	at cucumber.runner.Runner.runPickle(Runner.java:80)
	at cucumber.runtime.Runtime.runFeature(Runtime.java:119)
	at cucumber.runtime.Runtime.run(Runtime.java:104)
	at cucumber.api.cli.Main.run(Main.java:36)
	at cucumber.api.cli.Main.main(Main.java:18)
Caused by: groovy.json.JsonException: Lexing failed on line: 1, column: 1, while reading '<', no possible valid JSON value or punctuation could be recognized.
	at groovy.json.JsonLexer.nextToken(JsonLexer.java:83)
	at groovy.json.JsonLexer$nextToken.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:117)
	at io.restassured.internal.path.json.ConfigurableJsonSlurper.parse(ConfigurableJsonSlurper.groovy:97)
	at io.restassured.internal.path.json.ConfigurableJsonSlurper$parse.callCurrent(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:52)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:154)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:166)
	at io.restassured.internal.path.json.ConfigurableJsonSlurper.parseText(ConfigurableJsonSlurper.groovy:83)
	at io.restassured.path.json.JsonPath$4$1.method(JsonPath.java:893)
	at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:928)
	... 22 more
]]></failure>
</testcase>
<testcase classname="Jira Test With Single Scenario Outline" name="01. Validate user name for different sets of data 2" time="3.297508">
<system-out><![CDATA[Given Username is Test2.....................................................passed
]]></system-out>
</testcase>
<testcase classname="Jira Test With Single Scenario Outline" name="01. Validate user name for different sets of data 3" time="3.349169">
<system-out><![CDATA[Given Username is Test3.....................................................passed
]]></system-out>
</testcase>
<testcase classname="Jira Test With Single Scenario Outline" name="01. Validate user name for different sets of data 4" time="3.31696">
<system-out><![CDATA[Given Username is Test4.....................................................passed
]]></system-out>
</testcase>
<testcase classname="Jira Test With Single Scenario Outline" name="01. Validate user name for different sets of data 5" time="2.848293">
<system-out><![CDATA[Given Username is Test5.....................................................passed
]]></system-out>
</testcase>
</testsuite>
